server:
  port: ${SERVER_PORT:8080}

app:
  maintenance:
    message: "Sistema Operativo - Version 1.0"
management:
  endpoints:
    web:
      exposure:
        include: "refresh, health"

spring:
  threads:
    virtual:
      enabled: true
  mongodb:
    host: ${MONGO_HOST:localhost}
    port: ${MONGO_PORT:27017}
    database: ${MONGO_DATABASE:product-db}
    username: ${MONGO_USERNAME:root}
    password: ${MONGO_PASSWORD:password}
    authentication-database: ${MONGO_AUTH_DB:admin}
  web:
    error:
      include-stacktrace: never
      include-message: always

eureka:
  client:
      service-url:
        defaultZone: http://localhost:8761/eureka/