server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:////Users/mzrt/Coding/ms-shop/config-data
          clone-on-start: true
          default-label: main